-deraceclockdata
+cli+force
+define+build
+error+100
+noautonaming 
+noautoudp 
-full64 
+libverbose 
+noprune+gates+prims+cell
+svext+.sv
+sv  
+timescale+override+1ns/1ps
+vcs+initreg+random
#+maxdelays 
+neg_tchk
+no_tchk_msg
+cli+force
-debug_access+all
+nocelldefinepli+0
-debug_region+cell
-debug_region+cellports
+notimingchecks
+define+FUNCTIONAL
#+define+tmax_serial
+verbose
${SDENV_FSIM_ELABORATION_INTERNAL_STROBER_FILE}
# enable portfaults
+suppress+cell
+nolibcell
${SDENV_FSIM_LIB_GL}
${SDENV_SYNTH_SYNTHESIZED_LIB_PATH}/${SDENV_DESIGN}.v